on:
  push:
    tags: ['v*']
permissions:
#  actions: write  # for artifact removal
  contents: write  # for release creation
env:
  REGISTRY: ghcr.io
jobs:
  build-push:
    name: build and push image to ghcr.io
    runs-on: ubuntu-latest
    steps:
    - name: Checkout commit
      uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        wget -qO - https://repo.radeon.com/rocm/rocm.gpg.key | sudo apt-key add -

        echo 'deb [arch=amd64] https://repo.radeon.com/rocm/apt/debian/ focal main' | sudo tee /etc/apt/sources.list.d/rocm.list
        sudo apt-get install rocm-dev

        sudo apt-get update
        make clean
        make
      working-directory: ./src

    - name: Login to ghcr.io
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ github.token }}
    - name: Extract Tag
      id: extract_tag
      run: echo "IMAGE_TAG=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
    - name: Build Docker image
      env:
        TAG: ${{ env.IMAGE_TAG }}
      run: make docker_build 
      working-directory: ./src
    - name: Push Docker image
      env:
        TAG: ${{ env.IMAGE_TAG }}
        IMAGE_NAME: ${{ github.repository }}
      run: make push 
      working-directory: ./src